# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  example-job:
    steps:
      - run: npm install -g bats
jobs:
  example-job:
    steps:
      - name: Run build script #referenced in the path saved in .github folder
        run: ./.github/scripts/build.sh
      - name: testing runner debug
        run: ACTIONS_RUNNER_DEBUG: true
        shell: bash
 
